on: [push]

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: PascalRombach/dnd-tables@master
        id: dnd-tables
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
